"""Agent 4 · Case Reporter.

Reads:  Agent 3's Q&A trace + decision, Agent 2's ring, Agent 1's graph stats.
Does:   assembles a SAR-ready case pack — a Markdown report and a self-contained
        printable HTML (Save-as-PDF) — re-walking the full evidence chain so a
        human can follow every step. This is the artifact the "Download case
        pack" button returns (R08); on demo day the narrated Trupeer video is
        dropped alongside it.
Writes: the finished, downloadable case-pack record back to the bus.

Every claim in the pack traces to a real edge or pattern Agent 2 computed.
"""

from __future__ import annotations

import html
from datetime import datetime, timezone

from ..bus import MemoryBus

NAMESPACE = "reporter"


def _ring(bus: MemoryBus, ring_id: str) -> dict:
    for r in bus.read("detective", "rings") or []:
        if r["ring_id"] == ring_id:
            return r
    raise ValueError(f"No such ring {ring_id}")


def build_markdown(bus: MemoryBus, ring_id: str) -> str:
    ring = _ring(bus, ring_id)
    graph = bus.read("grapher", "graph") or {}
    qa = bus.read("investigator", f"qa_{ring_id}") or []
    decision = bus.read("investigator", f"decision_{ring_id}") or {}
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    p = ring["patterns"]
    ow = ring["open_date_window"]
    tw = ring["time_window"] or {}

    lines = []
    a = lines.append
    a(f"# Suspicious Activity Report — Case {ring_id}")
    a("")
    a(f"*Generated by RingFinder · {now} · source dataset `{graph.get('source','?')}`*")
    a("")
    a("## 1. Summary")
    a("")
    a(f"- **Decision:** {decision.get('decision','(pending)').upper()}")
    a(f"- **Ring Risk Score:** {ring['risk_score']} (rank #{ring.get('rank','?')})")
    a(f"- **Accounts involved:** {ring['n_members']} — {', '.join(ring['members'])}")
    a(f"- **Aggregate exposure:** ${ring['aggregate_amount']:,.2f}")
    a(f"- **Internal transfers:** {ring['n_transfers']}")
    a(f"- **Coordinated loops:** {ring.get('n_subclusters', 1)}")
    a(f"- **Routing hub:** {ring['hub']}")
    if tw:
        a(f"- **Activity window:** {tw.get('first')} → {tw.get('last')}")
    a("")
    a("> Every account in this ring individually passed all threshold rules. "
      "The case was surfaced from transaction *topology*, not any single flagged transaction.")
    a("")

    a("## 2. Why this is a ring (computed evidence)")
    a("")
    a("| Pattern | Fired | Evidence |")
    a("|---|---|---|")
    label = {
        "circular": "Circular flow / layering",
        "mule": "Mule fan-in / fan-out",
        "cluster": "Coordinated cluster",
        "shared_identity": "Shared-identity bridge",
        "structuring": "Synchronized structuring",
        "centrality": "Centrality (routing hub)",
    }
    for key, name in label.items():
        pat = p[key]
        mark = "✅" if pat.get("fired") else "—"
        a(f"| {name} | {mark} | {pat.get('why','')} |")
    a("")

    a("## 3. Risk score breakdown")
    a("")
    a("| Component | Contribution |")
    a("|---|---|")
    for k, v in ring["score_breakdown"].items():
        a(f"| {k.replace('_',' ')} | {v} |")
    a(f"| **Total** | **{ring['risk_score']}** |")
    a("")

    a("## 4. Coordinated onboarding")
    a("")
    a(f"Ring accounts were opened between **{ow.get('first')}** and **{ow.get('last')}** "
      f"— a **{ow.get('span_days')}-day** window, consistent with a single operator "
      f"provisioning mule accounts in a batch.")
    a("")

    a("## 5. Money-flow ledger (sample)")
    a("")
    a("| Txn | From | To | Amount | Timestamp |")
    a("|---|---|---|---|---|")
    for e in sorted(ring["edges"], key=lambda x: x["timestamp"])[:25]:
        a(f"| {e['txn_id']} | {e['src']} | {e['dst']} | ${e['amount']:,.2f} | {e['timestamp']} |")
    if ring["n_transfers"] > 25:
        a(f"| … | | | | _{ring['n_transfers']-25} more transfers_ |")
    a("")

    if qa:
        a("## 6. Investigation Q&A trace")
        a("")
        for i, item in enumerate(qa, 1):
            a(f"**Q{i}.** {item['question']}")
            a("")
            a(f"**A.** {item['answer']}  ")
            a(f"*(grounded via {item['source']})*")
            a("")

    if decision.get("notes"):
        a("## 7. Analyst notes")
        a("")
        a(decision["notes"])
        a("")

    a("---")
    a("")
    a("*Prepared by RingFinder — a 4-agent pipeline (Grapher → Ring Detective → "
      "Investigator → Case Reporter) handing findings through a shared memory bus. "
      "This document is the downloadable case pack (MVP R08).*")
    return "\n".join(lines)


def build_html(markdown_text: str, ring_id: str) -> str:
    """Self-contained printable HTML (browser Save-as-PDF) — no extra deps."""
    try:
        from markdown_it import MarkdownIt

        body = MarkdownIt("commonmark", {"html": False}).enable("table").render(markdown_text)
    except Exception:
        body = "<pre>" + html.escape(markdown_text) + "</pre>"
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>SAR — {html.escape(ring_id)}</title>
<style>
  body {{ font: 15px/1.6 -apple-system, Segoe UI, Roboto, sans-serif; max-width: 820px;
         margin: 40px auto; padding: 0 24px; color: #1a1a2e; }}
  h1 {{ border-bottom: 3px solid #e63946; padding-bottom: 8px; }}
  h2 {{ margin-top: 32px; color: #1d3557; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 13px; }}
  th, td {{ border: 1px solid #cbd5e1; padding: 6px 10px; text-align: left; }}
  th {{ background: #f1f5f9; }}
  blockquote {{ border-left: 4px solid #e63946; margin: 16px 0; padding: 8px 16px;
               background: #fff5f5; color: #444; }}
  code {{ background: #f1f5f9; padding: 1px 5px; border-radius: 3px; }}
  @media print {{ body {{ margin: 0; }} }}
</style></head><body>{body}</body></html>"""


def run(bus: MemoryBus, ring_id: str) -> dict:
    bus.log("reporter", "read", f"loaded {ring_id} ring + Q&A + decision to assemble case pack")
    md = build_markdown(bus, ring_id)
    htmldoc = build_html(md, ring_id)
    record = {
        "ring_id": ring_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "markdown": md,
        "html": htmldoc,
        "filename_md": f"SAR_{ring_id}.md",
        "filename_html": f"SAR_{ring_id}.html",
        # Placeholder for the Trupeer narrated walkthrough dropped in on demo day.
        "video_note": "Trupeer narrated walkthrough attaches here in the case pack.",
    }
    bus.write(NAMESPACE, f"casepack_{ring_id}", record)
    bus.log("reporter", "write", f"assembled downloadable case pack for {ring_id} (SAR md+html)")
    return record


def get_casepack(bus: MemoryBus, ring_id: str) -> dict | None:
    return bus.read(NAMESPACE, f"casepack_{ring_id}")
